rive-app/rive-android

- cpp/src/bindings/bindings_linear_animation_instance.cpp
- kotlin/src/main/java/app/rive/runtime/kotlin/Animation.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/LinearAnimationInstance.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/Renderer.kt
> Small fixes

- build.gradle
- cpp/src/bindings/bindings_linear_animation_instance.cpp
- gradle/wrapper/gradle-wrapper.properties
Updates submodule, function signature, rebuild all `.so`s.
> Update C++ 

- app/src/main/res/layout/activity_main.xml
- cpp/src/bindings/bindings_aabb.cpp
- kotlin/src/main/java/app/rive/runtime/kotlin/AABB.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveDrawable.kt
rebased version of: https://github.com/rive-app/rive-android/pull/27
> Add bridge for AABB bounds

- kotlin/src/androidTest/java/app/rive/runtime/kotlin/RiveAnimationConfigurationsTest.kt
- kotlin/src/androidTest/java/app/rive/runtime/kotlin/RiveAnimationLoadTest.kt
- kotlin/src/androidTest/java/app/rive/runtime/kotlin/RiveArtboardLoadTest.kt
- kotlin/src/androidTest/java/app/rive/runtime/kotlin/RiveFileLoadTest.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/AABB.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/Animation.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/Artboard.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/File.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/LinearAnimationInstance.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/Renderer.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/Rive.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveDrawable.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveException.kt
update a load more documentation 
fixes #42 
also using properties wherever it seemed feasible.
> Documentation grab

- app/src/main/java/app/rive/runtime/example/MainActivity.kt
- cpp/build.rive.for.sh
- cpp/src/bindings/bindings_aabb.cpp
- cpp/src/bindings/bindings_artboard.cpp
- cpp/src/bindings/bindings_file.cpp
- cpp/src/bindings/bindings_init.cpp
- cpp/src/bindings/bindings_linear_animation.cpp
- cpp/src/bindings/bindings_linear_animation_instance.cpp
- cpp/src/bindings/bindings_renderer.cpp
- cpp/src/jni_refs.cpp
- kotlin/src/androidTest/java/app/rive/runtime/kotlin/core/RiveAnimationConfigurationsTest.kt
- kotlin/src/androidTest/java/app/rive/runtime/kotlin/core/RiveAnimationLoadTest.kt
- kotlin/src/androidTest/java/app/rive/runtime/kotlin/core/RiveArtboardLoadTest.kt
- kotlin/src/androidTest/java/app/rive/runtime/kotlin/core/RiveFileLoadTest.kt
- kotlin/src/androidTest/java/app/rive/runtime/kotlin/core/TestUtils.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveAnimationView.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveDrawable.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/AABB.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/Animation.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/Artboard.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/File.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/LinearAnimationInstance.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/Renderer.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/Rive.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/RiveException.kt
moving everything with cpp bindings into a core namespace
> reorganizing objects with cpp bindings into core section

- app/src/main/java/app/rive/runtime/example/MainActivity.kt
- app/src/main/res/layout/activity_main.xml
- cpp/include/models/dimensions_helper.hpp
- cpp/include/models/jni_renderer.hpp
- cpp/include/models/render_path.hpp
- cpp/src/bindings/bindings_helper.cpp
- cpp/src/models/dimensions_helper.cpp
- kotlin/src/androidTest/java/app/rive/runtime/kotlin/core/RiveUtilTest.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveAnimationView.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveDrawable.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/Rive.kt
- kotlin/src/main/res/values/attrs.xml
Another stepping stone. slightly reworked the View to no longer extend CompatImageView. (maybe we'll need to go back on this) but simply stick to View for now. 
also started to allow some configuration through the xml declarations. updated examples to use this. but we need a lot more examples with different layouts, and with / wihtout using the xml declaration. 
fixes #45
> 45 - update RiveAnimationView

- app/src/main/AndroidManifest.xml
- app/src/main/java/app/rive/runtime/example/AnimationsActivity.kt
- app/src/main/java/app/rive/runtime/example/BuggyActivity.kt
- app/src/main/java/app/rive/runtime/example/MainActivity.kt
- app/src/main/res/layout/buggy.xml
- app/src/main/res/layout/example_selection.xml
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveAnimationView.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveDrawable.kt
> 51 - allow pausing specific animations in view

- kotlin/src/androidTest/java/app/rive/runtime/kotlin/core/RiveAnimationLoadTest.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/Artboard.kt
pretty much what it says
fixes #31
> added get animationNames to artboards

- app/src/main/java/app/rive/runtime/example/LoopActivity.kt
- app/src/main/res/layout/loopy.xml
- cpp/src/bindings/bindings_linear_animation_instance.cpp
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveAnimationView.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveDrawable.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/Animation.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/LinearAnimationInstance.kt
dont merge until the cpp is merged
fixes #61
> update example with playing backwards!

- kotlin/src/androidTest/java/app/rive/runtime/kotlin/core/RiveViewTest.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveAnimationView.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveDrawable.kt
fixes #65 
adds the stop command to stop an animation (which is essentially pause and unload)
> add stop & tests

- cpp/build.rive.for.sh
> removed debug flag, saving us 6mb!

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/app/rive/runtime/example/MainActivity.kt
- app/src/main/java/app/rive/runtime/example/RiveFragment.kt
- app/src/main/java/app/rive/runtime/example/RiveFragmentActivity.kt
- app/src/main/java/app/rive/runtime/example/SimpleActivity.kt
- app/src/main/res/layout/activity_rive_fragment.xml
- app/src/main/res/layout/example_selection.xml
- app/src/main/res/layout/fragment_rive.xml
Experimenting with fragments wrapping animation views and controlling their lifecycles.
> Basic fragment wrapping a RiveAnimationView

- app/src/main/AndroidManifest.xml
- app/src/main/java/app/rive/runtime/example/LowLevelActivity.kt
- app/src/main/java/app/rive/runtime/example/MainActivity.kt
- app/src/main/res/layout/activity_low_level.xml
- app/src/main/res/layout/example_selection.xml
> Adds simple low level rendering example

- kotlin/src/main/res/values/attrs.xml
fixes orders of fit attrs to line up with the rest of the code
> fixed order of fit attrs

- app/src/main/java/app/rive/runtime/example/AndroidPlayerActivity.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveAnimationView.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveDrawable.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/Animation.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/LinearAnimationInstance.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/Loop.kt
does what it says on the tin. 
fixes #112
> renamed Loop.NONE to Loop.AUTO

- README.md
updated readme to mention draw order
resolves #108
> updated readme to talk about animation order

- app/build.gradle
- app/src/main/java/app/rive/runtime/example/SimpleActivity.kt
- app/src/main/res/layout/simple.xml
- kotlin/build.gradle
- kotlin/src/main/AndroidManifest.xml
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveAnimationView.kt
- kotlin/src/main/res/values/attrs.xml
Also updates some dependency versions.
Volley is now a dependency.
> Adds high level constructor for Rive files over http

- app/src/main/java/app/rive/runtime/example/AndroidPlayerActivity.kt
- kotlin/src/androidTest/java/app/rive/runtime/kotlin/core/RiveEventTest.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveDrawable.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/AnimationState.kt
> update statechanged callback to use state machine name, and state name

- app/src/main/java/app/rive/runtime/example/SimpleStateMachineActivity.kt
- kotlin/src/androidTest/java/app/rive/runtime/kotlin/core/RiveEventTest.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/AnimationState.kt
another update to remove AnimationState:
> update state changed callback to just the animation name

- .github/workflows/tests.yml
- app/build.gradle
- app/src/main/java/app/rive/runtime/example/LayoutActivity.kt
- app/src/main/java/app/rive/runtime/example/utils/RiveSwitch.kt
- kotlin/build.gradle
removed android-extensions that we didn't seem to be using anyways
checking into github actions
fixes #137
(trying to see if i can test this without getting it into master... i think with the pr we might be able to...)
> add running tests to on push/pr tests

- kotlin/src/main/java/app/rive/runtime/kotlin/RiveAnimationView.kt
Fixes an issue where the animation no longer plays when reattaching to the window.
Not super sure how to test this. I think there must be a way to trigger the onDetach and onAttach callbacks, but struggling to work it out. Putting this up for feedback in the mean time. Tested a similar implementation via the react native runtime however and it's fixed the issue.
> Track playing animations on detach from window

- .github/workflows/release.yml
- .github/workflows/tests.yml
- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- kotlin/build.gradle
bumping kotlin/ gradle versions. I had problems with react native once I did this, so going to go over there and see if this works too... 
also curious if this is going to cause problems with build scripts..
> chore: bump gradle and kotlin

- cpp/src/helpers/EGLThreadState.cpp
> fix: adds alpha channel to egl

- .github/scripts/release/package-lock.json
- .github/scripts/release/package.json
updating release-it dependency to update a dependency our auto release tool has and is causing a warning banner on our lib
> chore: pushed up release-it vesion tto resolve ansi-regex vulnerability

- app/src/main/java/app/rive/runtime/example/AndroidPlayerActivity.kt
- app/src/main/java/app/rive/runtime/example/MetricsActivity.kt
- cpp/include/models/jni_renderer_skia.hpp
- cpp/src/bindings/bindings_animation_view.cpp
- cpp/src/bindings/bindings_renderer.cpp
- kotlin/src/androidTest/java/app/rive/runtime/kotlin/core/RiveAnimationConfigurationsTest.kt
- kotlin/src/androidTest/java/app/rive/runtime/kotlin/core/RiveViewTest.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveAnimationView.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveDrawable.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/File.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/StateMachineInstance.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/renderers/BaseRenderer.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/renderers/RendererSkia.kt
- Perform UI updates on UI thread
- Fix the cleanup step so the Renderer gets deallocated
- Make sure we queue another callback when we're running
- Let `RiveAnimationView` initialize Swappy (and comment out `RenderMetrics` for now)
- Few other minor things
> Miscellaneous fixes

- cpp/build.rive.for.sh
- cpp/include/helpers/general.hpp
- cpp/src/bindings/bindings_animation_view.cpp
- cpp/src/bindings/bindings_init.cpp
- cpp/src/bindings/bindings_renderer.cpp
- cpp/src/helpers/general.cpp
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveAnimationView.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveDrawable.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/Artboard.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/File.kt
- Fix `onMeasure()`for surface view
- Add `DEBUG` flag that removes `LOG`s and logging `thread`
> Swappy measure

- README.md
- app/build.gradle
- app/src/main/java/app/rive/runtime/example/AndroidPlayerActivity.kt
- app/src/main/java/app/rive/runtime/example/LowLevelActivity.kt
- app/src/main/java/app/rive/runtime/example/utils/RiveButton.kt
- app/src/main/java/app/rive/runtime/example/utils/RiveSwitch.kt
- app/src/main/res/layout/activity_low_level.xml
- build.gradle
- cpp/src/bindings/bindings_animation_view.cpp
- kotlin/build.gradle
- kotlin/src/androidTest/java/app/rive/runtime/kotlin/core/RiveEventTest.kt
- kotlin/src/androidTest/java/app/rive/runtime/kotlin/core/RiveViewStateMachineTest.kt
- kotlin/src/androidTest/java/app/rive/runtime/kotlin/core/RiveViewTest.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveAnimationView.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveArtboardRenderer.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveDrawable.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveSurfaceHolder.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveSurfaceView.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/Artboard.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/renderers/BaseRenderer.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/renderers/RendererSkia.kt
Add the `RiveSurfaceView` abstraction, rename `RiveDrawable` to `RiveArtboardRenderer` 
Reinstate debug mode for debug builds in our gradle
> Swappy surface holder

- app/src/main/AndroidManifest.xml
- app/src/main/java/app/rive/runtime/example/ButtonActivity.kt
- app/src/main/java/app/rive/runtime/example/MainActivity.kt
- app/src/main/java/app/rive/runtime/example/utils/RiveButton.kt
- app/src/main/res/layout/button.xml
- app/src/main/res/layout/example_selection.xml
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveAnimationView.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveSurfaceView.kt
- updated measure to use artboard size when no size provided
- moved isrunning into surfaceview
- make rivebutton extend riveanimationview
- added metrics to menu
> Android patches

- kotlin/build.gradle
- kotlin/proguard-rules.pro
- kotlin/src/main/AndroidManifest.xml
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveAnimationView.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/controllers/RiveController.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/renderers/RendererMetrics.kt
will rebase on https://github.com/rive-app/rive-android/pull/202 once merged. 
just addresses the things i ran into using our lib for the piggy bank app
> Smallv2fixes

- app/src/main/java/app/rive/runtime/example/LowLevelActivity.kt
- cpp/include/bindings/bindings_renderer.hpp
- cpp/src/bindings/bindings_artboard.cpp
- cpp/src/bindings/bindings_renderer.cpp
- kotlin/src/main/java/app/rive/runtime/kotlin/RiveArtboardRenderer.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/core/Artboard.kt
- kotlin/src/main/java/app/rive/runtime/kotlin/renderers/RendererSkia.kt
what i think we need to do with the drawSkia piece
*probably dont merge, more for talking point*
> tore the drawSkia piece apart a bit

- cpp/include/helpers/tracer.hpp
- cpp/include/models/jni_renderer_skia.hpp
- cpp/src/models/jni_renderer_skia.cpp
Also, some housekeeping for `JNIRendererSkia`.
Fixes #218
> Fix FPS counter

- app/src/main/java/app/rive/runtime/example/MetricsActivity.kt
- cpp/build.all.sh
- cpp/build.rive.for.sh
Use updated lib folder structure for submodule dependencies.
Depends on https://github.com/rive-app/rive-cpp/pull/131
> Updated build folders

- cpp/include/helpers/egl_thread_state.hpp
- cpp/include/helpers/general.hpp
- cpp/src/helpers/egl_thread_state.cpp
- cpp/src/helpers/general.cpp
Just some QoL improvements that I had left in the other experimental branch.
These changes don't affect our `.so`s since they are debug-only.
> Improve logging for debug and add EGL error checks

- cpp/include/helpers/egl_thread_state.hpp
- cpp/include/helpers/worker_thread.hpp
- cpp/src/bindings/bindings_rive_texture_view.cpp
- cpp/src/helpers/egl_thread_state.cpp
- cpp/src/models/jni_renderer_skia.cpp
We've received reports of the Settings singleton causing crashes. Since we're not currently using it, I've resorted to removing all references to it altogether (class is still there, if we want to start using it again in the future).
> Remove Leftovers

- .github/workflows/submodule_check.yml
just going to merge this once it passes
> update submodule check

- build.gradle
- cpp/src/bindings/bindings_helper.cpp
- gradle/wrapper/gradle-wrapper.properties
Do we care about Gradle version? When I was building, Android Studio suggested I upgrade ...
> Roll cpp, update gradle
